version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post-build:
    commands:
      - aws s3 cp --recursive ./build s3://www.oncloudconsulting/
      - aws cloudfront create-invalidation --distribution-id E12G59HB9FP52O --path /\*
